/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search flights across providers
         * @description Fans out concurrently to all configured providers (currently Amadeus).
         *     Results are deduplicated by flight number + departure time, ranked by
         *     price ascending, and cached in Redis for 10 minutes.
         */
        get: operations["searchFlights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example true */
            ok: boolean;
            /** @example wanderly-search */
            service: string;
        };
        /** @description RFC 7807 Problem Details */
        ProblemDetails: {
            /** @example 400 */
            status: number;
            /** @example Missing parameters */
            title: string;
            /** @example origin, destination, and date are required */
            detail?: string;
        };
        FlightSlice: {
            /** @example RUH */
            origin: string;
            /** @example HND */
            destination: string;
            /**
             * Format: date-time
             * @example 2026-08-12T18:40:00Z
             */
            depart: string;
            /**
             * Format: date-time
             * @example 2026-08-13T09:55:00Z
             */
            arrive: string;
            /** @example SV */
            carrier: string;
            /** @example SV802 */
            flightNum: string;
            /**
             * @description Flight duration in minutes
             * @example 795
             */
            duration: number;
            /**
             * @description Number of stops on this leg
             * @example 0
             */
            stops: number;
        };
        FlightOffer: {
            /**
             * @description Provider-assigned offer ID — required for QuoteOffer and Confirm calls
             * @example 1
             */
            id: string;
            /** @example amadeus */
            provider: string;
            /**
             * @description Total price in the smallest currency unit (cents for USD/SAR)
             * @example 145600
             */
            totalCents: number;
            /** @example USD */
            currency: string;
            slices: components["schemas"]["FlightSlice"][];
            /** @example false */
            refundable: boolean;
            /**
             * @description True for the cheapest offer in the result set
             * @example true
             */
            bestValue: boolean;
            /**
             * Format: date-time
             * @description Offer expiry — must re-quote after this time before confirming
             * @example 2026-08-12T19:10:00Z
             */
            expiresAt: string;
        };
        FlightSearchResponse: {
            data: components["schemas"]["FlightOffer"][];
            /** @example 12 */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    searchFlights: {
        parameters: {
            query: {
                /** @description Departure airport IATA code */
                origin: string;
                /** @description Arrival airport IATA code */
                destination: string;
                /** @description Departure date (YYYY-MM-DD) */
                date: string;
                adults?: number;
                cabin?: "economy" | "premium" | "business" | "first";
                /** @description Return date for round trips (omit for one-way) */
                returnDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ranked flight offers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSearchResponse"];
                };
            };
            /** @description Missing or invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Provider error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Search service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
